FROM node:14-alpine as build
WORKDIR /frontend
ENV PATH /frontend/node_modules/.bin:$PATH
COPY ./package.json /frontend/
RUN yarn
COPY . /frontend
RUN yarn build

# stage 2 - build the final image and copy the react build files
FROM nginx
COPY --from=build /frontend/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]